// Vinprofil: stilreferanse. Typiske smaksprofiler for vanlige vinstiler.
// d = [fylde, syre, tannin, sødme, frukt, eik] på skala 1–5.
// a = aliaser som gjenkjennes i navn, produsent, region eller drue (små bokstaver, aksenter ignoreres).
// g = 1: bred druestil, brukes bare når ingen mer spesifikk stil passer.
// Verdiene er et utgangspunkt; den konkrete vinen kan avvike, og Vinmonopolets klokker vinner når de finnes.
window.VIN_STYLES = [
  // ---------- Rødt: Frankrike ----------
  { id: "bordeaux-venstre", n: "Bordeaux, venstre bredd", t: "rød", d: [4, 3, 4, 1, 3, 4], a: ["medoc", "haut-medoc", "pauillac", "margaux", "saint-julien", "st-julien", "saint-estephe", "st-estephe", "pessac-leognan", "listrac", "moulis"], p: "Cabernet-dominert med solbær, sedertre og faste tanniner." },
  { id: "bordeaux-hoyre", n: "Bordeaux, høyre bredd", t: "rød", d: [4, 3, 3, 1, 4, 4], a: ["saint-emilion", "st-emilion", "pomerol", "lalande-de-pomerol", "fronsac", "castillon"], p: "Merlot-dominert med plomme, kirsebær og mykere tanniner." },
  { id: "bordeaux", n: "Bordeaux", t: "rød", d: [3, 3, 3, 1, 3, 2], a: ["bordeaux", "bordeaux superieur", "bordeaux rouge", "cotes de bordeaux", "blaye"], p: "Middels fyldig blend med rødbær, urter og moderate tanniner." },
  { id: "cahors", n: "Cahors", t: "rød", d: [5, 3, 5, 1, 4, 3], a: ["cahors"], p: "Mørk Malbec med blåbær, lakris og kraftige tanniner." },
  { id: "madiran", n: "Madiran", t: "rød", d: [5, 3, 5, 1, 3, 3], a: ["madiran", "tannat"], p: "Tannat med svært faste tanniner, mørk frukt og jordlige toner." },
  { id: "bourgogne-rouge", n: "Bourgogne rouge", t: "rød", d: [2, 4, 2, 1, 3, 2], a: ["bourgogne rouge", "bourgogne pinot noir", "hautes-cotes de nuits", "hautes-cotes de beaune", "coteaux bourguignons"], p: "Lett Pinot Noir med rips, kirsebær og frisk syre." },
  { id: "cote-de-nuits", n: "Côte de Nuits", t: "rød", d: [3, 4, 3, 1, 3, 3], a: ["gevrey-chambertin", "chambolle-musigny", "vosne-romanee", "nuits-saint-georges", "morey-saint-denis", "vougeot", "marsannay", "fixin", "chambertin", "clos de la roche", "richebourg"], p: "Strukturert Pinot Noir med kirsebær, krydder og skogbunn." },
  { id: "cote-de-beaune-rouge", n: "Côte de Beaune rød", t: "rød", d: [3, 4, 3, 1, 3, 3], a: ["pommard", "volnay", "beaune", "savigny-les-beaune", "aloxe-corton", "corton", "santenay", "monthelie", "auxey-duresses", "chorey-les-beaune"], p: "Pinot Noir med rød frukt, fin syre og silkemyk struktur." },
  { id: "chalonnaise-rouge", n: "Côte Chalonnaise rød", t: "rød", d: [2, 4, 2, 1, 3, 2], a: ["mercurey", "givry", "rully rouge"], p: "Rimeligere Bourgogne med rød frukt og frisk syre." },
  { id: "beaujolais", n: "Beaujolais", t: "rød", d: [2, 4, 1, 1, 4, 1], a: ["beaujolais", "beaujolais-villages", "beaujolais villages", "beaujolais nouveau"], p: "Saftig Gamay med jordbær og bringebær, nesten uten tanniner." },
  { id: "beaujolais-cru", n: "Beaujolais cru", t: "rød", d: [3, 4, 2, 1, 4, 1], a: ["morgon", "fleurie", "moulin-a-vent", "brouilly", "cote de brouilly", "julienas", "chiroubles", "saint-amour", "chenas", "regnie"], p: "Gamay med mer dybde, kirsebær, blomster og lett struktur." },
  { id: "rhone-nord", n: "Nordlige Rhône", t: "rød", d: [4, 4, 4, 1, 4, 3], a: ["cote-rotie", "cote rotie", "hermitage", "cornas"], p: "Syrah med mørke bær, pepper, oliven og fast struktur." },
  { id: "crozes-st-joseph", n: "Crozes-Hermitage og Saint-Joseph", t: "rød", d: [3, 4, 3, 1, 4, 2], a: ["crozes-hermitage", "crozes hermitage", "saint-joseph", "st-joseph"], p: "Saftig Syrah med bjørnebær, pepper og frisk syre." },
  { id: "cotes-du-rhone", n: "Côtes du Rhône", t: "rød", d: [3, 3, 3, 1, 4, 1], a: ["cotes du rhone", "cotes-du-rhone", "cotes du rhone villages", "ventoux", "luberon", "costieres de nimes"], p: "Grenache-blend med moden rød frukt, krydder og myk struktur." },
  { id: "chateauneuf", n: "Châteauneuf-du-Pape", t: "rød", d: [5, 2, 3, 1, 5, 2], a: ["chateauneuf-du-pape", "chateauneuf du pape", "chateauneuf"], p: "Varm, fyldig Grenache med moden frukt, garrigue og høy alkohol." },
  { id: "gigondas", n: "Gigondas og nabolandsbyer", t: "rød", d: [4, 3, 4, 1, 4, 2], a: ["gigondas", "vacqueyras", "rasteau", "cairanne", "lirac", "vinsobres"], p: "Kraftig sørlig Rhône med mørk frukt, urter og faste tanniner." },
  { id: "languedoc", n: "Languedoc og Roussillon", t: "rød", d: [4, 3, 3, 1, 4, 2], a: ["languedoc", "pic saint-loup", "faugeres", "saint-chinian", "minervois", "corbieres", "fitou", "terrasses du larzac", "roussillon", "pays d'oc"], p: "Solmoden blend med mørke bær, urter og krydder." },
  { id: "bandol-rouge", n: "Bandol rød", t: "rød", d: [4, 3, 5, 1, 3, 2], a: ["bandol rouge"], p: "Mourvèdre med lær, mørk frukt og kraftige tanniner." },
  { id: "loire-cabernet-franc", n: "Loire Cabernet Franc", t: "rød", d: [2, 4, 3, 1, 3, 1], a: ["chinon", "bourgueil", "saint-nicolas-de-bourgueil", "saumur-champigny", "saumur rouge", "anjou rouge"], p: "Lett og frisk med bringebær, paprika og grafitt." },
  { id: "sancerre-rouge", n: "Sancerre rouge", t: "rød", d: [2, 4, 2, 1, 3, 1], a: ["sancerre rouge"], p: "Lett Pinot Noir med kirsebær og høy syre." },
  // ---------- Rødt: Italia ----------
  { id: "barolo", n: "Barolo", t: "rød", d: [4, 5, 5, 1, 3, 2], a: ["barolo"], p: "Nebbiolo med rose, tjære, kirsebær, høy syre og stramme tanniner." },
  { id: "barbaresco", n: "Barbaresco", t: "rød", d: [4, 5, 4, 1, 3, 2], a: ["barbaresco"], p: "Nebbiolo litt mer elegant enn Barolo, med rose og røde bær." },
  { id: "langhe-nebbiolo", n: "Langhe Nebbiolo", t: "rød", d: [3, 4, 4, 1, 3, 1], a: ["langhe nebbiolo", "nebbiolo d'alba", "nebbiolo dalba", "roero"], p: "Yngre Nebbiolo med rose, kirsebær og merkbare tanniner." },
  { id: "alto-piemonte", n: "Alto Piemonte og Valtellina", t: "rød", d: [3, 5, 4, 1, 3, 2], a: ["gattinara", "ghemme", "boca", "lessona", "bramaterra", "valtellina", "sforzato", "sfursat", "inferno", "sassella", "grumello"], p: "Kjølig Nebbiolo med høy syre, rose og fjellurter." },
  { id: "barbera", n: "Barbera", t: "rød", d: [3, 5, 2, 1, 4, 2], a: ["barbera d'alba", "barbera d'asti", "barbera", "nizza"], p: "Saftig med kirsebær, høy syre og myke tanniner." },
  { id: "dolcetto", n: "Dolcetto", t: "rød", d: [3, 3, 3, 1, 4, 1], a: ["dolcetto", "dogliani"], p: "Myk og fruktig med plomme, mandel og lav syre." },
  { id: "chianti", n: "Chianti", t: "rød", d: [3, 4, 3, 1, 3, 2], a: ["chianti", "chianti classico", "chianti rufina", "chianti colli senesi"], p: "Sangiovese med kirsebær, tomatblad og frisk syre." },
  { id: "chianti-riserva", n: "Chianti Classico Riserva", t: "rød", d: [4, 4, 4, 1, 3, 3], a: ["chianti classico riserva", "chianti riserva", "gran selezione"], p: "Mer konsentrert Sangiovese med lær, kirsebær og faste tanniner." },
  { id: "brunello", n: "Brunello di Montalcino", t: "rød", d: [4, 4, 4, 1, 3, 3], a: ["brunello di montalcino", "brunello"], p: "Kraftig Sangiovese med kirsebær, lær, tobakk og lang struktur." },
  { id: "rosso-montalcino", n: "Rosso di Montalcino", t: "rød", d: [3, 4, 3, 1, 4, 2], a: ["rosso di montalcino"], p: "Yngre Sangiovese fra Montalcino, saftig og frisk." },
  { id: "montepulciano-nobile", n: "Vino Nobile di Montepulciano", t: "rød", d: [3, 4, 3, 1, 3, 2], a: ["vino nobile di montepulciano", "vino nobile", "rosso di montepulciano"], p: "Sangiovese med plomme, krydder og moderat struktur." },
  { id: "super-tuscan", n: "Bolgheri og supertoscanere", t: "rød", d: [4, 3, 4, 1, 4, 4], a: ["bolgheri", "super tuscan", "supertoscaner", "sassicaia", "tignanello", "ornellaia", "guado al tasso", "toscana igt"], p: "Bordeaux-druer i Toscana: solbær, eik og fast, polert struktur." },
  { id: "montepulciano-abruzzo", n: "Montepulciano d'Abruzzo", t: "rød", d: [3, 3, 3, 1, 4, 1], a: ["montepulciano d'abruzzo", "montepulciano dabruzzo"], p: "Rund og fruktig med plomme og myke tanniner." },
  { id: "amarone", n: "Amarone", t: "rød", d: [5, 3, 4, 2, 5, 3], a: ["amarone", "amarone della valpolicella"], p: "Tørkede druer gir rosin, kirsebær, sjokolade og høy alkohol." },
  { id: "ripasso", n: "Valpolicella Ripasso", t: "rød", d: [4, 3, 3, 2, 4, 2], a: ["ripasso", "valpolicella ripasso"], p: "Fyldigere Valpolicella med moden kirsebær og et hint av sødme." },
  { id: "valpolicella", n: "Valpolicella", t: "rød", d: [2, 4, 2, 1, 3, 1], a: ["valpolicella", "valpolicella classico", "valpolicella superiore", "bardolino"], p: "Lett og frisk med kirsebær og mandel." },
  { id: "primitivo", n: "Primitivo", t: "rød", d: [5, 2, 3, 2, 5, 2], a: ["primitivo", "primitivo di manduria"], p: "Fyldig og moden med syltetøy, plomme og myk syre." },
  { id: "salento", n: "Negroamaro og Salice Salentino", t: "rød", d: [4, 3, 3, 1, 4, 1], a: ["negroamaro", "salice salentino", "salento"], p: "Mørk frukt, urter og en jordlig, myk struktur." },
  { id: "nero-davola", n: "Nero d'Avola", t: "rød", d: [4, 3, 3, 1, 4, 1], a: ["nero d'avola", "nero davola", "cerasuolo di vittoria"], p: "Siciliansk med mørke kirsebær, plomme og krydder." },
  { id: "etna-rosso", n: "Etna Rosso", t: "rød", d: [3, 4, 3, 1, 3, 1], a: ["etna rosso", "nerello mascalese", "etna"], p: "Vulkansk og elegant med rød frukt, røyk og frisk syre." },
  { id: "aglianico", n: "Aglianico og Taurasi", t: "rød", d: [4, 4, 5, 1, 3, 2], a: ["taurasi", "aglianico del vulture", "aglianico"], p: "Mørk og stram med kirsebær, tobakk og kraftige tanniner." },
  { id: "lambrusco", n: "Lambrusco", t: "rød", d: [2, 4, 2, 2, 4, 1], a: ["lambrusco"], p: "Musserende rødvin med bringebær, frisk syre og ofte litt sødme." },
  // ---------- Rødt: Spania og Portugal ----------
  { id: "rioja", n: "Rioja Crianza", t: "rød", d: [3, 3, 3, 1, 3, 3], a: ["rioja", "rioja crianza", "crianza"], p: "Tempranillo med kirsebær, vanilje og amerikansk eik." },
  { id: "rioja-reserva", n: "Rioja Reserva og Gran Reserva", t: "rød", d: [3, 3, 3, 1, 3, 4], a: ["rioja reserva", "rioja gran reserva", "gran reserva"], p: "Modnet Tempranillo med lær, tørket frukt, vanilje og dill." },
  { id: "ribera", n: "Ribera del Duero", t: "rød", d: [4, 3, 4, 1, 4, 4], a: ["ribera del duero", "ribera"], p: "Kraftig Tempranillo med mørke bær, eik og faste tanniner." },
  { id: "toro", n: "Toro", t: "rød", d: [5, 3, 5, 1, 4, 3], a: ["toro", "tinta de toro"], p: "Svært konsentrert Tempranillo med mørk frukt og kraftige tanniner." },
  { id: "priorat", n: "Priorat og Montsant", t: "rød", d: [5, 3, 4, 1, 5, 3], a: ["priorat", "priorato", "montsant"], p: "Konsentrert Garnacha og Cariñena med mørk frukt og skifermineralitet." },
  { id: "garnacha", n: "Spansk Garnacha", t: "rød", d: [4, 2, 2, 1, 5, 1], a: ["campo de borja", "calatayud", "carinena", "garnacha", "navarra"], p: "Moden og saftig med jordbær, bringebær og myk struktur." },
  { id: "monastrell", n: "Monastrell", t: "rød", d: [5, 2, 3, 1, 5, 2], a: ["jumilla", "yecla", "alicante", "monastrell"], p: "Varm og fyldig med mørke bær, plomme og urter." },
  { id: "bierzo", n: "Mencía (Bierzo)", t: "rød", d: [3, 4, 3, 1, 4, 1], a: ["bierzo", "mencia", "ribeira sacra", "valdeorras"], p: "Frisk og blomstrete med rød frukt og mineralitet." },
  { id: "douro-tinto", n: "Douro rødvin", t: "rød", d: [4, 3, 4, 1, 4, 3], a: ["douro", "douro tinto"], p: "Mørk og kraftig med bjørnebær, fioler og faste tanniner." },
  { id: "dao", n: "Dão", t: "rød", d: [3, 4, 3, 1, 3, 2], a: ["dao", "touriga nacional"], p: "Elegant portugisisk med rød frukt, blomster og frisk syre." },
  { id: "alentejo", n: "Alentejo", t: "rød", d: [4, 2, 3, 1, 5, 2], a: ["alentejo", "alentejano"], p: "Solmoden og myk med moden mørk frukt." },
  // ---------- Rødt: Tyskland og Østerrike ----------
  { id: "spatburgunder", n: "Spätburgunder", t: "rød", d: [2, 4, 2, 1, 3, 2], a: ["spatburgunder", "spaetburgunder"], p: "Tysk Pinot Noir, lett og frisk med kirsebær." },
  { id: "blaufrankisch", n: "Blaufränkisch", t: "rød", d: [3, 4, 3, 1, 4, 2], a: ["blaufrankisch", "blaufraenkisch", "lemberger", "kekfrankos"], p: "Mørke kirsebær, pepper og frisk syre." },
  { id: "zweigelt", n: "Zweigelt", t: "rød", d: [2, 3, 2, 1, 4, 1], a: ["zweigelt"], p: "Lett og saftig med kirsebær og et snev pepper." },
  // ---------- Rødt: Den nye verden ----------
  { id: "napa-cabernet", n: "Napa Cabernet", t: "rød", d: [5, 2, 4, 1, 5, 4], a: ["napa", "napa valley"], p: "Kraftig og moden med solbær, vanilje og polerte tanniner." },
  { id: "california-pinot", n: "Californisk Pinot Noir", t: "rød", d: [3, 3, 2, 1, 4, 3], a: ["sonoma", "russian river", "sta. rita hills", "santa rita hills", "carneros", "santa lucia"], p: "Moden Pinot Noir med kirsebær, cola og eik." },
  { id: "zinfandel", n: "Zinfandel", t: "rød", d: [5, 2, 3, 2, 5, 3], a: ["zinfandel", "lodi"], p: "Syltetøyaktig og krydret med høy alkohol." },
  { id: "oregon-pinot", n: "Oregon Pinot Noir", t: "rød", d: [2, 4, 2, 1, 4, 2], a: ["willamette", "oregon", "dundee hills"], p: "Kjølig Pinot Noir med tranebær, kirsebær og frisk syre." },
  { id: "malbec-argentina", n: "Argentinsk Malbec", t: "rød", d: [4, 3, 3, 1, 5, 3], a: ["malbec", "mendoza", "uco valley", "lujan de cuyo"], p: "Fyldig og myk med plomme, blåbær og fioler." },
  { id: "carmenere", n: "Carmenère", t: "rød", d: [4, 2, 3, 1, 4, 2], a: ["carmenere"], p: "Mørk frukt med grønn pepper og myke tanniner." },
  { id: "shiraz-australia", n: "Australsk Shiraz", t: "rød", d: [5, 2, 3, 1, 5, 3], a: ["barossa", "mclaren vale", "shiraz", "clare valley shiraz"], p: "Fyldig og moden med bjørnebær, lakris og sjokolade." },
  { id: "pinotage", n: "Pinotage", t: "rød", d: [4, 3, 3, 1, 4, 2], a: ["pinotage"], p: "Sørafrikansk med mørk frukt, røyk og jordlige toner." },
  { id: "nz-pinot", n: "New Zealand Pinot Noir", t: "rød", d: [3, 4, 2, 1, 4, 2], a: ["central otago", "martinborough", "marlborough pinot noir"], p: "Ren og fruktig Pinot Noir med kirsebær og frisk syre." },
  { id: "chile-cabernet", n: "Chilensk Cabernet", t: "rød", d: [4, 3, 3, 1, 4, 3], a: ["maipo", "colchagua", "cachapoal", "rapel"], p: "Solbær, mynte og moderat eik." },
  // ---------- Rødt: brede druestiler ----------
  { id: "cabernet-sauvignon", n: "Cabernet Sauvignon", t: "rød", d: [4, 3, 4, 1, 4, 3], a: ["cabernet sauvignon", "cabernet"], p: "Solbær, sedertre og faste tanniner.", g: 1 },
  { id: "merlot", n: "Merlot", t: "rød", d: [3, 3, 3, 1, 4, 2], a: ["merlot"], p: "Myk og rund med plomme og kirsebær.", g: 1 },
  { id: "pinot-noir", n: "Pinot Noir", t: "rød", d: [2, 4, 2, 1, 3, 2], a: ["pinot noir"], p: "Lett og elegant med rød frukt og frisk syre.", g: 1 },
  { id: "syrah", n: "Syrah", t: "rød", d: [4, 3, 3, 1, 4, 2], a: ["syrah"], p: "Mørke bær, pepper og middels til kraftig struktur.", g: 1 },
  { id: "grenache", n: "Grenache", t: "rød", d: [4, 2, 2, 1, 5, 1], a: ["grenache"], p: "Moden rød frukt, krydder og myk struktur.", g: 1 },
  { id: "tempranillo", n: "Tempranillo", t: "rød", d: [3, 3, 3, 1, 3, 3], a: ["tempranillo", "tinto fino", "tinta roriz"], p: "Kirsebær, lær og ofte eik.", g: 1 },
  { id: "sangiovese", n: "Sangiovese", t: "rød", d: [3, 4, 3, 1, 3, 2], a: ["sangiovese"], p: "Kirsebær, urter og frisk syre.", g: 1 },
  { id: "nebbiolo", n: "Nebbiolo", t: "rød", d: [4, 5, 5, 1, 3, 2], a: ["nebbiolo"], p: "Rose, tjære, høy syre og stramme tanniner.", g: 1 },
  { id: "cabernet-franc", n: "Cabernet Franc", t: "rød", d: [3, 4, 3, 1, 3, 2], a: ["cabernet franc"], p: "Bringebær, paprika og frisk struktur.", g: 1 },
  { id: "gamay", n: "Gamay", t: "rød", d: [2, 4, 1, 1, 4, 1], a: ["gamay"], p: "Saftig og lett med røde bær.", g: 1 },
  { id: "rodvin", n: "Rødvin", t: "rød", d: [3, 3, 3, 1, 3, 2], a: ["rodvin", "red wine", "vin rouge", "rosso", "tinto"], p: "Middels fyldig rødvin.", g: 1 },

  // ---------- Hvitt: Frankrike ----------
  { id: "chablis", n: "Chablis", t: "hvit", d: [2, 5, 1, 1, 2, 1], a: ["chablis", "petit chablis"], p: "Stålfrisk Chardonnay med sitrus, grønt eple og flint." },
  { id: "chablis-cru", n: "Chablis Premier og Grand Cru", t: "hvit", d: [3, 5, 1, 1, 3, 2], a: ["chablis 1er cru", "chablis premier cru", "chablis grand cru", "montmains", "vaillons", "fourchaume", "montee de tonnerre", "les clos", "vaudesir", "valmur"], p: "Mer konsentrert Chablis med sitrus, østersskall og lengde." },
  { id: "bourgogne-blanc", n: "Bourgogne blanc", t: "hvit", d: [3, 4, 1, 1, 3, 2], a: ["bourgogne blanc", "bourgogne chardonnay", "bourgogne aligote", "aligote"], p: "Frisk Chardonnay med eple, sitrus og lett nøtt." },
  { id: "cote-de-beaune-blanc", n: "Côte de Beaune hvit", t: "hvit", d: [4, 4, 1, 1, 3, 4], a: ["meursault", "puligny-montrachet", "chassagne-montrachet", "saint-aubin", "corton-charlemagne", "montrachet", "batard-montrachet", "saint-romain"], p: "Fyldig Chardonnay med smør, hasselnøtt, sitrus og eik." },
  { id: "maconnais", n: "Mâconnais", t: "hvit", d: [3, 3, 1, 1, 3, 2], a: ["macon", "macon-villages", "pouilly-fuisse", "saint-veran", "vire-clesse", "pouilly-loche", "pouilly-vinzelles"], p: "Rund Chardonnay med moden eple, melon og litt eik." },
  { id: "sancerre", n: "Sancerre og Pouilly-Fumé", t: "hvit", d: [2, 5, 1, 1, 3, 1], a: ["sancerre", "pouilly-fume", "pouilly fume", "menetou-salon", "quincy", "reuilly", "touraine sauvignon"], p: "Sauvignon Blanc med sitrus, stikkelsbær og flint." },
  { id: "loire-chenin", n: "Loire Chenin Blanc", t: "hvit", d: [3, 5, 1, 2, 3, 1], a: ["vouvray", "savennieres", "montlouis", "saumur blanc", "anjou blanc"], p: "Chenin med eple, honning, ull og høy syre, fra tørr til halvtørr." },
  { id: "muscadet", n: "Muscadet", t: "hvit", d: [1, 4, 1, 1, 2, 1], a: ["muscadet", "muscadet sevre et maine", "melon de bourgogne"], p: "Lett og saltaktig med sitrus, perfekt til skalldyr." },
  { id: "alsace-riesling", n: "Alsace Riesling", t: "hvit", d: [3, 5, 1, 1, 3, 1], a: ["alsace riesling", "riesling alsace"], p: "Tørr Riesling med lime, petroleum og mineralitet." },
  { id: "gewurztraminer", n: "Gewürztraminer", t: "hvit", d: [4, 2, 1, 3, 5, 1], a: ["gewurztraminer", "gewuerztraminer", "traminer"], p: "Aromatisk med litchi, rose og ofte litt sødme." },
  { id: "pinot-gris-alsace", n: "Pinot Gris (Alsace)", t: "hvit", d: [4, 3, 1, 2, 4, 1], a: ["pinot gris"], p: "Fyldig med pære, honning og røyk." },
  { id: "bordeaux-blanc", n: "Hvit Bordeaux", t: "hvit", d: [3, 4, 1, 1, 3, 2], a: ["bordeaux blanc", "entre-deux-mers", "graves blanc", "pessac-leognan blanc"], p: "Sauvignon og Sémillon med sitrus, gress og voks." },
  { id: "viognier", n: "Viognier og Condrieu", t: "hvit", d: [4, 2, 1, 1, 5, 2], a: ["condrieu", "viognier"], p: "Fyldig og aromatisk med aprikos, fersken og blomster." },
  { id: "rhone-blanc", n: "Hvit Rhône", t: "hvit", d: [4, 3, 1, 1, 4, 2], a: ["cotes du rhone blanc", "chateauneuf-du-pape blanc", "hermitage blanc", "marsanne", "roussanne"], p: "Fyldig med steinfrukt, nøtter og urter." },
  { id: "picpoul", n: "Picpoul de Pinet", t: "hvit", d: [2, 4, 1, 1, 2, 1], a: ["picpoul de pinet", "picpoul"], p: "Lett og sitrusfrisk, laget for østers." },
  { id: "jura-savagnin", n: "Jura og Vin Jaune", t: "hvit", d: [4, 4, 1, 1, 3, 2], a: ["vin jaune", "savagnin", "arbois", "cotes du jura"], p: "Nøtteaktig og oksidativ med karri og valnøtt." },
  // ---------- Hvitt: Tyskland og Østerrike ----------
  { id: "riesling-trocken", n: "Riesling trocken", t: "hvit", d: [3, 5, 1, 1, 4, 1], a: ["riesling trocken", "trocken", "grosses gewachs", "erstes gewachs", "smaragd"], p: "Tørr Riesling med fersken, lime og skiferpreg." },
  { id: "riesling-kabinett", n: "Riesling Kabinett", t: "hvit", d: [2, 5, 1, 3, 4, 1], a: ["kabinett"], p: "Lett, halvtørr Riesling med grønt eple og høy syre." },
  { id: "riesling-spatlese", n: "Riesling Spätlese", t: "hvit", d: [3, 5, 1, 4, 4, 1], a: ["spatlese", "spaetlese"], p: "Søtlig Riesling med fersken, honning og frisk syre." },
  { id: "riesling", n: "Riesling", t: "hvit", d: [2, 5, 1, 2, 4, 1], a: ["riesling", "mosel", "rheingau", "nahe", "pfalz", "clare valley", "eden valley"], p: "Høy syre med sitrus, steinfrukt og ofte litt sødme.", g: 1 },
  { id: "gruner", n: "Grüner Veltliner", t: "hvit", d: [3, 4, 1, 1, 3, 1], a: ["gruner veltliner", "grüner veltliner", "gruener veltliner", "wachau", "kamptal", "kremstal", "weinviertel"], p: "Hvit pepper, grønne erter, sitrus og frisk syre." },
  // ---------- Hvitt: Italia, Spania, Portugal ----------
  { id: "soave", n: "Soave", t: "hvit", d: [2, 3, 1, 1, 3, 1], a: ["soave", "garganega"], p: "Lett og mandelaktig med pære og sitrus." },
  { id: "pinot-grigio", n: "Pinot Grigio", t: "hvit", d: [2, 3, 1, 1, 2, 1], a: ["pinot grigio"], p: "Lett og nøytral med pære og sitrus." },
  { id: "gavi", n: "Gavi", t: "hvit", d: [2, 4, 1, 1, 2, 1], a: ["gavi", "cortese"], p: "Frisk og lett med sitrus og mandel." },
  { id: "verdicchio", n: "Verdicchio", t: "hvit", d: [2, 4, 1, 1, 3, 1], a: ["verdicchio"], p: "Sitrus, mandel og en lett bitter avslutning." },
  { id: "vermentino", n: "Vermentino", t: "hvit", d: [2, 4, 1, 1, 3, 1], a: ["vermentino", "rolle"], p: "Sitrus, urter og salt havbris." },
  { id: "sor-italia-hvit", n: "Fiano, Greco og Falanghina", t: "hvit", d: [3, 4, 1, 1, 3, 1], a: ["fiano di avellino", "fiano", "greco di tufo", "falanghina"], p: "Mer struktur med steinfrukt, nøtter og røyk." },
  { id: "etna-bianco", n: "Etna Bianco", t: "hvit", d: [2, 5, 1, 1, 3, 1], a: ["etna bianco", "carricante"], p: "Vulkansk og stram med sitrus og salt." },
  { id: "albarino", n: "Albariño", t: "hvit", d: [2, 5, 1, 1, 3, 1], a: ["albarino", "albariño", "rias baixas", "alvarinho"], p: "Fersken, sitrus og salt friskhet." },
  { id: "rueda", n: "Rueda Verdejo", t: "hvit", d: [2, 4, 1, 1, 3, 1], a: ["rueda", "verdejo"], p: "Frisk med sitrus, fennikel og en lett bitterhet." },
  { id: "godello", n: "Godello", t: "hvit", d: [3, 4, 1, 1, 3, 2], a: ["godello"], p: "Mineralsk med eple, sitrus og noe fylde." },
  { id: "vinho-verde", n: "Vinho Verde", t: "hvit", d: [1, 4, 1, 2, 3, 1], a: ["vinho verde"], p: "Lett, ofte lett perlende, med sitrus og litt sødme." },
  // ---------- Hvitt: Den nye verden og brede stiler ----------
  { id: "nz-sauvignon", n: "New Zealand Sauvignon Blanc", t: "hvit", d: [2, 5, 1, 1, 5, 1], a: ["marlborough", "awatere"], p: "Intens pasjonsfrukt, stikkelsbær og gress." },
  { id: "chardonnay-ny-verden", n: "Chardonnay, ny verden", t: "hvit", d: [4, 3, 1, 1, 4, 4], a: ["napa chardonnay", "sonoma chardonnay", "margaret river chardonnay", "adelaide hills", "russian river chardonnay"], p: "Fyldig med tropisk frukt, vanilje og smør." },
  { id: "chenin-sa", n: "Sørafrikansk Chenin Blanc", t: "hvit", d: [3, 4, 1, 1, 4, 2], a: ["swartland", "stellenbosch chenin"], p: "Saftig med gult eple, honning og frisk syre." },
  { id: "torrontes", n: "Torrontés", t: "hvit", d: [2, 3, 1, 1, 5, 1], a: ["torrontes"], p: "Blomstrete og aromatisk med muskat og sitrus." },
  { id: "hunter-semillon", n: "Hunter Semillon", t: "hvit", d: [1, 5, 1, 1, 2, 1], a: ["hunter valley semillon", "hunter semillon"], p: "Lett og knusktørr med sitrus, som får toast med alder." },
  { id: "chardonnay", n: "Chardonnay", t: "hvit", d: [3, 3, 1, 1, 3, 3], a: ["chardonnay"], p: "Eple og sitrus, ofte med smør og eik.", g: 1 },
  { id: "sauvignon-blanc", n: "Sauvignon Blanc", t: "hvit", d: [2, 5, 1, 1, 4, 1], a: ["sauvignon blanc", "sauvignon"], p: "Frisk med sitrus, stikkelsbær og gress.", g: 1 },
  { id: "chenin-blanc", n: "Chenin Blanc", t: "hvit", d: [3, 4, 1, 2, 4, 1], a: ["chenin blanc", "chenin"], p: "Eple, honning og høy syre.", g: 1 },
  { id: "pinot-blanc", n: "Pinot Blanc", t: "hvit", d: [2, 3, 1, 1, 2, 1], a: ["pinot blanc", "weissburgunder", "pinot bianco"], p: "Myk og mild med eple og mandel.", g: 1 },
  { id: "hvitvin", n: "Hvitvin", t: "hvit", d: [2, 4, 1, 1, 3, 1], a: ["hvitvin", "white wine", "vin blanc", "bianco", "blanco"], p: "Frisk hvitvin.", g: 1 },

  // ---------- Rosé ----------
  { id: "provence-rose", n: "Provence rosé", t: "rosé", d: [2, 4, 1, 1, 3, 1], a: ["cotes de provence", "provence rose", "coteaux d'aix", "coteaux varois"], p: "Blek og tørr med jordbær, fersken og sitrus." },
  { id: "bandol-rose", n: "Bandol rosé", t: "rosé", d: [3, 4, 1, 1, 3, 1], a: ["bandol rose"], p: "Strukturert rosé med rød frukt, urter og salt." },
  { id: "tavel", n: "Tavel", t: "rosé", d: [4, 3, 2, 1, 4, 1], a: ["tavel"], p: "Kraftig og mørk rosé med kirsebær og krydder." },
  { id: "rose", n: "Rosé", t: "rosé", d: [2, 4, 1, 1, 3, 1], a: ["rose", "rosado", "rosato", "rosevin"], p: "Tørr og frisk med røde bær.", g: 1 },

  // ---------- Musserende ----------
  { id: "champagne", n: "Champagne brut", t: "musserende", d: [3, 5, 1, 1, 3, 1], a: ["champagne", "brut reserve", "brut nature", "extra brut"], p: "Sitrus, grønt eple, brioche og fine bobler." },
  { id: "champagne-bdb", n: "Champagne Blanc de Blancs", t: "musserende", d: [2, 5, 1, 1, 3, 1], a: ["blanc de blancs"], p: "Ren Chardonnay med sitron, kritt og eleganse." },
  { id: "champagne-rose", n: "Champagne rosé", t: "musserende", d: [3, 5, 1, 1, 4, 1], a: ["champagne rose", "rose champagne", "brut rose"], p: "Jordbær og bringebær med frisk syre og brioche." },
  { id: "champagne-vintage", n: "Champagne årgang og prestige", t: "musserende", d: [4, 4, 1, 1, 3, 2], a: ["millesime", "vintage champagne", "cuvee prestige", "dom perignon", "cristal", "grande annee", "la grande dame"], p: "Mer modnet med nøtter, honning, toast og lengde." },
  { id: "cremant", n: "Crémant", t: "musserende", d: [2, 5, 1, 1, 3, 1], a: ["cremant", "cremant de bourgogne", "cremant de loire", "cremant d'alsace", "cremant du jura", "cremant de limoux"], p: "Champagne-metoden utenfor Champagne: frisk sitrus og eple." },
  { id: "cava", n: "Cava", t: "musserende", d: [2, 4, 1, 1, 2, 1], a: ["cava", "corpinnat"], p: "Tørr med sitrus, eple og en jordlig tone." },
  { id: "prosecco", n: "Prosecco", t: "musserende", d: [2, 3, 1, 2, 4, 1], a: ["prosecco", "valdobbiadene", "conegliano", "glera"], p: "Lett og fruktig med pære, eple og blomster." },
  { id: "franciacorta", n: "Franciacorta", t: "musserende", d: [3, 4, 1, 1, 3, 1], a: ["franciacorta", "trentodoc", "trento doc"], p: "Italiensk flaskegjæret med eple, mandel og brioche." },
  { id: "moscato-dasti", n: "Moscato d'Asti", t: "musserende", d: [1, 3, 1, 4, 5, 1], a: ["moscato d'asti", "moscato dasti", "asti spumante", "asti"], p: "Søt, lett perlende med druer, fersken og blomster." },
  { id: "musserende", n: "Musserende", t: "musserende", d: [2, 4, 1, 1, 3, 1], a: ["musserende", "sparkling", "sekt", "spumante", "espumoso", "pet-nat", "petillant naturel"], p: "Frisk musserende vin.", g: 1 },

  // ---------- Søtt og sterkvin ----------
  { id: "sauternes", n: "Sauternes og Barsac", t: "søt", d: [5, 3, 1, 5, 5, 3], a: ["sauternes", "barsac", "loupiac", "monbazillac"], p: "Edelråtne druer gir aprikos, honning og marmelade." },
  { id: "tokaji", n: "Tokaji Aszú", t: "søt", d: [4, 5, 1, 5, 5, 2], a: ["tokaji", "tokaj", "aszu"], p: "Søt og syrlig med aprikos, appelsinskall og honning." },
  { id: "riesling-edelsot", n: "Auslese og Beerenauslese", t: "søt", d: [3, 5, 1, 5, 5, 1], a: ["auslese", "beerenauslese", "trockenbeerenauslese"], p: "Søt Riesling med honning, fersken og høy syre." },
  { id: "isvin", n: "Isvin", t: "søt", d: [3, 5, 1, 5, 5, 1], a: ["eiswein", "icewine", "ice wine"], p: "Konsentrert sødme med tropisk frukt og frisk syre." },
  { id: "port-ruby", n: "Portvin Ruby og LBV", t: "søt", d: [5, 2, 4, 5, 5, 1], a: ["port", "portvin", "porto", "ruby", "late bottled vintage", "lbv"], p: "Søt og kraftig med mørke bær, plomme og sjokolade." },
  { id: "port-tawny", n: "Tawny portvin", t: "søt", d: [4, 3, 2, 5, 4, 3], a: ["tawny", "10 year old tawny", "20 year old tawny", "colheita"], p: "Fatmodnet med nøtter, karamell og tørket frukt." },
  { id: "port-vintage", n: "Vintage portvin", t: "søt", d: [5, 3, 5, 4, 5, 1], a: ["vintage port", "quinta do"], p: "Svært konsentrert med mørk frukt og kraftige tanniner." },
  { id: "sherry-fino", n: "Fino og Manzanilla", t: "hvit", d: [2, 3, 1, 1, 2, 1], a: ["fino", "manzanilla"], p: "Knusktørr sherry med mandel, salt og gjærpreg." },
  { id: "sherry-oloroso", n: "Amontillado og Oloroso", t: "hvit", d: [4, 3, 1, 1, 3, 3], a: ["amontillado", "oloroso", "palo cortado"], p: "Tørr, nøtteaktig sherry med valnøtt, karamell og krydder." },
  { id: "sherry-sot", n: "Pedro Ximénez og Cream", t: "søt", d: [5, 2, 1, 5, 5, 2], a: ["pedro ximenez", "cream sherry", "px"], p: "Sirupsaktig søt med rosin, fiken og sjokolade." },
  { id: "madeira", n: "Madeira", t: "søt", d: [4, 5, 1, 3, 4, 2], a: ["madeira", "malmsey", "bual", "verdelho madeira", "sercial"], p: "Høy syre med karamell, nøtter og tørket frukt." },
  { id: "vin-santo", n: "Vin Santo", t: "søt", d: [4, 3, 1, 4, 4, 2], a: ["vin santo"], p: "Tørkede druer gir nøtter, aprikos og honning." },
  { id: "recioto", n: "Recioto", t: "søt", d: [5, 3, 3, 5, 5, 2], a: ["recioto"], p: "Søt rødvin av tørkede druer med kirsebær og sjokolade." },
  { id: "dessertvin", n: "Dessertvin", t: "søt", d: [4, 3, 1, 5, 5, 1], a: ["dessertvin", "dessert wine", "vin doux", "late harvest", "vendanges tardives"], p: "Søt med moden frukt og honning.", g: 1 },

  // ---------- Oransje ----------
  { id: "qvevri", n: "Georgisk qvevri", t: "oransje", d: [3, 3, 4, 1, 3, 1], a: ["qvevri", "rkatsiteli", "kisi", "mtsvane", "georgia", "kakheti"], p: "Skallkontakt i leirkrukker: tørket frukt, te og tanniner." },
  { id: "oransje", n: "Oransjevin", t: "oransje", d: [3, 4, 3, 1, 3, 1], a: ["oransjevin", "orange wine", "skin contact", "macerated", "ramato"], p: "Hvite druer med skallkontakt: aprikos, te og litt tanniner.", g: 1 },
];
